### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [ccml/bapi-p3-the-scoop#4]
This was a very clean and organized project as the code was well written and it showed through the (almost) flawless functionality of your The Scoop site.

++ Consistent with indentations and whitespace.
++ Addition of efficient comments.
++ Necessary functionalities present (except 1).
++ Bonus attempt successful.

-- Editing comments does not work.

Overall, superb work! Keep it up!
Grade: Exceeds expectation!

**Comment by ccml** [comment]
Thanks for the feedback !
